---
# Service call documentation for Aigues de Barcelona integration

reset_and_refresh_data:
  name: Reset and Refresh Data
  description: WARNING! Reset all stored historic/metrics data and start getting metrics from 1 year ago, querying data weekly.
